import type { Wallet, Category, TransactionWithDetails } from '@/types'

export const MOCK_WALLETS: Wallet[] = [
  {
    id: 'w1',
    name: 'Main Wallet',
    type: 'cash',
    currency: 'USD',
    initial_balance: 1000,
    is_default: true,
    color: '#6366f1',
  },
  {
    id: 'w2',
    name: 'Savings',
    type: 'bank',
    currency: 'USD',
    initial_balance: 5000,
    is_default: false,
    color: '#8b5cf6',
  },
]

export const MOCK_CATEGORIES: Category[] = [
  { id: 'c1', name: 'Food', type: 'expense', icon: 'Utensils', color: '#f97316' },
  { id: 'c2', name: 'Transport', type: 'expense', icon: 'Car', color: '#3b82f6' },
  { id: 'c3', name: 'Salary', type: 'income', icon: 'Briefcase', color: '#10b981' },
  { id: 'c4', name: 'Entertainment', type: 'expense', icon: 'Gamepad2', color: '#ec4899' },
  { id: 'c5', name: 'Shopping', type: 'expense', icon: 'ShoppingBag', color: '#8b5cf6' },
]

export const MOCK_TRANSACTIONS: TransactionWithDetails[] = [
  {
    id: 't1',
    wallet_id: 'w1',
    category_id: 'c1',
    type: 'expense',
    amount: 25.5,
    date: '2026-04-10',
    description: "Lunch at Joe's",
    wallet: MOCK_WALLETS[0]!,
    category: MOCK_CATEGORIES[0]!,
  },
  {
    id: 't2',
    wallet_id: 'w1',
    category_id: 'c2',
    type: 'expense',
    amount: 15.0,
    date: '2026-04-10',
    description: 'Uber to office',
    wallet: MOCK_WALLETS[0]!,
    category: MOCK_CATEGORIES[1]!,
  },
  {
    id: 't3',
    wallet_id: 'w2',
    category_id: 'c3',
    type: 'income',
    amount: 3500.0,
    date: '2026-04-01',
    description: 'Monthly Salary',
    is_recurrence: true,
    recurrence: {
      id: 'r1',
      wallet_id: 'w2',
      category_id: 'c3',
      type: 'income',
      amount: 3500.0,
      description: 'Monthly Salary',
      frequency: 'monthly',
      start_date: '2026-01-01',
      is_active: true,
    },
    wallet: MOCK_WALLETS[1]!,
    category: MOCK_CATEGORIES[2]!,
  },
  {
    id: 't4',
    wallet_id: 'w1',
    category_id: 'c4',
    type: 'expense',
    amount: 60.0,
    date: '2026-04-09',
    description: 'Movie night',
    wallet: MOCK_WALLETS[0]!,
    category: MOCK_CATEGORIES[3]!,
  },
  {
    id: 't5',
    wallet_id: 'w1',
    category_id: 'c5',
    type: 'expense',
    amount: 120.0,
    date: '2026-04-08',
    description: 'New sneakers',
    wallet: MOCK_WALLETS[0]!,
    category: MOCK_CATEGORIES[4]!,
  },
]
