name: Tests
on:
  push:
    branches:
      - beta
      - main
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  test:
    name: test
    uses: ./.github/workflows/setup-api.yml
    with:
      command: composer tests
